apiVersion: v1
kind: Service
metadata:
  name: tbs-cms-frontend
  namespace: tbs-erp
  labels:
    app.kubernetes.io/name: tbs-cms-frontend
    app.kubernetes.io/component: cms
    app.kubernetes.io/part-of: tbs-erp-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tbs-cms-frontend
    app.kubernetes.io/component: cms
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
