-- #07 Kho — Kiện — Lô — Container, Task 1 (23/09/2026).
-- Generated by `prisma migrate diff` against a throwaway shadow DB
-- (`shadow_kho_07`, dropped after use) and hand-copied verbatim below — the
-- diff contains ONLY new CREATE TYPE / CREATE TABLE / CREATE INDEX
-- statements, no DROP and no ALTER of any table belonging to another module
-- (#01–#06). Verified by reading the generated script before copying it.
--
-- 8 new tables (all currently empty on tbs_test): tbl_khotq_receipts,
-- tbl_po_packing_lot, tbl_po_packing_lot_item, tbl_transport_files,
-- tbl_transport_file_items, tbl_transport_file_packages,
-- tbl_transport_package_contents, tbl_package_issue.
--
-- ⚠⚠⚠ enum KhoTqReceiptSource PHẢI đủ 5 giá trị (manual/lark/po_scan/
-- unclaimed/claimed) — 'unclaimed' từng THIẾU trên prod và chặn cả luồng
-- vô chủ → nhận chủ (xem plan mục "⚠ ĐO PROD" + comment trong schema.prisma).
--
-- ⚠ split_status/split_parent_id/... trên tbl_khotq_receipts CHƯA có service
-- dùng đợt này (prod đo split_status=0 ở 100% dòng) — cột vẫn giữ để một
-- lần migrate dữ liệu thật không mất gì.

-- CreateEnum
CREATE TYPE "KhoTqReceiptSource" AS ENUM ('manual', 'lark', 'po_scan', 'unclaimed', 'claimed');

-- CreateEnum
CREATE TYPE "TransportType" AS ENUM ('cont_ghep', 'duong_bo', 'duong_bien', 'duong_sat', 'duong_hang_khong');

-- CreateEnum
CREATE TYPE "CargoType" AS ENUM ('ghep', 'nguyen');

-- CreateTable
CREATE TABLE "tbl_khotq_receipts" (
    "id" SERIAL NOT NULL,
    "receipt_code" VARCHAR(100),
    "tracking_code" VARCHAR(100),
    "po_id" INTEGER,
    "po_item_id" INTEGER,
    "lot_id" INTEGER,
    "order_id" INTEGER,
    "customer_id" VARCHAR(20),
    "kho" VARCHAR(24),
    "product_name" VARCHAR(500),
    "quantity" INTEGER,
    "packages" INTEGER,
    "weight" DECIMAL(10,2),
    "volume" DECIMAL(10,4),
    "status" INTEGER NOT NULL DEFAULT 1,
    "condition_status" VARCHAR(20),
    "temp_location" TEXT,
    "container_item_id" INTEGER,
    "file_id" INTEGER,
    "code_khotq" TEXT,
    "lark_record_id" TEXT,
    "client_ref" TEXT,
    "source" "KhoTqReceiptSource",
    "split_status" INTEGER NOT NULL DEFAULT 0,
    "split_parent_id" INTEGER,
    "split_seq" INTEGER,
    "split_req_by" TEXT,
    "split_req_at" INTEGER,
    "split_req_note" TEXT,
    "split_by" TEXT,
    "split_at" INTEGER,
    "split_note" TEXT,
    "split_xnk_by" TEXT,
    "split_xnk_at" INTEGER,
    "split_on_cont" INTEGER,
    "received_by" TEXT,
    "received_at" INTEGER,
    "notes" TEXT,

    CONSTRAINT "tbl_khotq_receipts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tbl_po_packing_lot" (
    "id" SERIAL NOT NULL,
    "po_id" INTEGER NOT NULL,
    "lot_no" INTEGER NOT NULL,
    "supplier_name" VARCHAR(255),
    "plan_packages" INTEGER,
    "plan_qty_per_pack" DECIMAL(15,2),
    "plan_spec" TEXT,
    "plan_weight_kg" DECIMAL(12,2),
    "plan_cbm" DECIMAL(12,4),
    "expected_ready_date" DATE,
    "claim_note" TEXT,
    "claim_at" INTEGER,
    "claim_by" TEXT,
    "label_need" INTEGER,
    "label_by" TEXT,
    "label_qty" INTEGER,
    "label_note" TEXT,
    "supplier_note" TEXT,

    CONSTRAINT "tbl_po_packing_lot_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tbl_po_packing_lot_item" (
    "id" SERIAL NOT NULL,
    "lot_id" INTEGER NOT NULL,
    "po_item_id" INTEGER,
    "product_name" TEXT,
    "quantity" DECIMAL(15,2),
    "unit" TEXT,

    CONSTRAINT "tbl_po_packing_lot_item_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tbl_transport_files" (
    "id" SERIAL NOT NULL,
    "file_code" VARCHAR(50),
    "route" TEXT,
    "truck_bill_no" TEXT,
    "transport_type" "TransportType",
    "cargo_type" "CargoType",
    "status" INTEGER NOT NULL DEFAULT 0,
    "classification" TEXT,
    "pack_date" DATE,
    "lock_deadline" DATE,
    "pack_date_actual" DATE,
    "run_date" DATE,
    "port_arrival_date" DATE,
    "arrival_date" DATE,
    "arrival_date_actual" DATE,
    "clearance_date" DATE,
    "settled_at" INTEGER,
    "total_weight" DECIMAL(12,2),
    "total_volume" DECIMAL(12,4),
    "total_packages" INTEGER,
    "total_orders" INTEGER,
    "total_customers" INTEGER,
    "total_cost" DECIMAL(15,2),
    "total_declared_value" DECIMAL(15,2),
    "cont_size" TEXT,
    "max_volume" DECIMAL(65,30),
    "max_weight" DECIMAL(65,30),
    "packing_list_sent_at" INTEGER,
    "packing_list_sent_by" TEXT,
    "packing_confirmed_at" INTEGER,
    "packing_confirmed_by" TEXT,
    "customs_locked" INTEGER NOT NULL DEFAULT 0,
    "customs_locked_by" TEXT,
    "customs_locked_at" INTEGER,
    "customs_gate" TEXT,
    "vehicle_type" TEXT,
    "vehicle_code" TEXT,
    "assigned_to" TEXT,
    "created_by" TEXT,
    "created_at" INTEGER,
    "closed_by" TEXT,
    "closed_at" INTEGER,

    CONSTRAINT "tbl_transport_files_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tbl_transport_file_items" (
    "id" SERIAL NOT NULL,
    "file_id" INTEGER NOT NULL,
    "product_name" TEXT,
    "quantity" DECIMAL(15,2),
    "unit" TEXT,

    CONSTRAINT "tbl_transport_file_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tbl_transport_file_packages" (
    "id" SERIAL NOT NULL,
    "file_id" INTEGER NOT NULL,
    "package_code" TEXT,
    "weight" DECIMAL(10,2),
    "volume" DECIMAL(10,4),

    CONSTRAINT "tbl_transport_file_packages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tbl_transport_package_contents" (
    "id" SERIAL NOT NULL,
    "package_id" INTEGER NOT NULL,
    "file_id" INTEGER,
    "item_id" INTEGER,
    "order_id" INTEGER,
    "customer_id" TEXT,
    "quantity" DECIMAL(15,2),
    "net_weight" DECIMAL(10,2),

    CONSTRAINT "tbl_transport_package_contents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tbl_package_issue" (
    "id" SERIAL NOT NULL,
    "package_id" INTEGER NOT NULL,
    "khau" VARCHAR(20),
    "reasons" VARCHAR(255),
    "note" VARCHAR(500),
    "created_by" VARCHAR(50),
    "created_at" INTEGER,
    "ack_by" VARCHAR(50),
    "ack_at" INTEGER,
    "ack_note" VARCHAR(500),
    "closed_by" VARCHAR(50),
    "closed_at" INTEGER,
    "close_note" VARCHAR(500),

    CONSTRAINT "tbl_package_issue_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "tbl_khotq_receipts_tracking_code_idx" ON "tbl_khotq_receipts"("tracking_code");

-- CreateIndex
CREATE INDEX "tbl_khotq_receipts_po_id_idx" ON "tbl_khotq_receipts"("po_id");

-- CreateIndex
CREATE INDEX "tbl_khotq_receipts_po_item_id_idx" ON "tbl_khotq_receipts"("po_item_id");

-- CreateIndex
CREATE INDEX "tbl_khotq_receipts_order_id_idx" ON "tbl_khotq_receipts"("order_id");

-- CreateIndex
CREATE INDEX "tbl_khotq_receipts_kho_idx" ON "tbl_khotq_receipts"("kho");

-- CreateIndex
CREATE INDEX "tbl_khotq_receipts_status_idx" ON "tbl_khotq_receipts"("status");

-- CreateIndex
CREATE INDEX "tbl_khotq_receipts_file_id_idx" ON "tbl_khotq_receipts"("file_id");

-- CreateIndex
CREATE INDEX "tbl_khotq_receipts_client_ref_idx" ON "tbl_khotq_receipts"("client_ref");

-- CreateIndex
CREATE INDEX "tbl_po_packing_lot_po_id_idx" ON "tbl_po_packing_lot"("po_id");

-- CreateIndex
CREATE UNIQUE INDEX "tbl_po_packing_lot_po_id_lot_no_key" ON "tbl_po_packing_lot"("po_id", "lot_no");

-- CreateIndex
CREATE INDEX "tbl_po_packing_lot_item_lot_id_idx" ON "tbl_po_packing_lot_item"("lot_id");

-- CreateIndex
CREATE INDEX "tbl_transport_files_status_idx" ON "tbl_transport_files"("status");

-- CreateIndex
CREATE INDEX "tbl_transport_files_assigned_to_idx" ON "tbl_transport_files"("assigned_to");

-- CreateIndex
CREATE INDEX "tbl_transport_files_created_at_idx" ON "tbl_transport_files"("created_at");

-- CreateIndex
CREATE INDEX "tbl_transport_file_items_file_id_idx" ON "tbl_transport_file_items"("file_id");

-- CreateIndex
CREATE INDEX "tbl_transport_file_packages_file_id_idx" ON "tbl_transport_file_packages"("file_id");

-- CreateIndex
CREATE INDEX "tbl_transport_package_contents_package_id_idx" ON "tbl_transport_package_contents"("package_id");

-- CreateIndex
CREATE INDEX "tbl_package_issue_package_id_idx" ON "tbl_package_issue"("package_id");
