-- #07 Kho — review cuối (F3/F6, schema A1+A2), 23/09/2026.
-- Generated by `prisma migrate diff` against a throwaway shadow DB
-- (`shadow_kho_f3f6`, dropped after use) and hand-copied verbatim below — a
-- SINGLE ALTER TABLE (ADD COLUMN + ALTER COLUMN ... DROP NOT NULL) + one
-- CREATE INDEX. No DROP, no data-destroying rewrite of any column, no touch
-- of any other table.
--
-- ⚠⚠⚠ A1 — `file_id` Int -> Int? (DROP NOT NULL, NOT drop+add): prod
-- `tbl_transport_file_packages.file_id` uses sentinel 0 = "received but not
-- yet loaded onto a transport file" on 1.510/1.568 rows (96.3%) — the
-- DOMINANT state, not an edge case. The column must allow NULL so the
-- upcoming ETL (which maps that sentinel to NULL) does not violate NOT NULL
-- mid-run. `ALTER COLUMN "file_id" DROP NOT NULL` preserves every existing
-- row exactly as-is — it does not rewrite or move any data.
--
-- ⚠⚠⚠ A2 — new nullable `khotq_receipt_id` (+ index): prod
-- `tbl_transport_file_packages.khotq_receipt_id` is a populated FK on 100%
-- (1.568/1.568) of rows — without it a package on a container can never be
-- traced back to its receiving receipt, customer, or order (this is why
-- TransportFile.totalCustomers/totalOrders were uncomputable). Nullable
-- because this migration does not backfill data — `ADD COLUMN` on an
-- existing table with no default is a metadata-only change (fast, no table
-- rewrite on Postgres for a nullable column with NULL default).
ALTER TABLE "tbl_transport_file_packages"
  ADD COLUMN "khotq_receipt_id" INTEGER,
  ALTER COLUMN "file_id" DROP NOT NULL;

CREATE INDEX "tbl_transport_file_packages_khotq_receipt_id_idx" ON "tbl_transport_file_packages"("khotq_receipt_id");
