-- #08 Hải quan — Task 1 (schema + migration), 23/09/2026.
-- Generated by `prisma migrate diff` against a throwaway shadow DB
-- (`shadow_customs_task1`, dropped after use) and hand-copied verbatim
-- below — two CREATE TYPE, one ALTER TABLE (ADD COLUMN only) on
-- `tbl_transport_file_items`, four CREATE TABLE, and CREATE INDEX. No DROP,
-- no data-destroying rewrite of any column, no touch of any table outside
-- `tbl_transport_file_items` (#07, extended here) and the four new #08
-- tables.
--
-- ⚠ CustomsChannel: prod column is `enum('','green','yellow','red')`. Prisma
-- cannot have an empty enum member name, so the schema names the empty
-- value `KHONG` and `@map("")`s it back to the real empty string below —
-- `CREATE TYPE "CustomsChannel" AS ENUM ('', 'green', 'yellow', 'red')`
-- stores the literal empty string, matching prod's channel='' on 248/248
-- measured rows (the flow has never run).
--
-- ⚠ tbl_customs_declarations / tbl_import_goods keep several columns for
-- workflows measured as NEVER RUN on prod (frozen_json/frozen_at,
-- hq_precheck_*, pending_json/pending_by/pending_at, hs_status default 0) —
-- kept so a future data migration loses nothing, no service built for them
-- this task.

-- CreateEnum
CREATE TYPE "CustomsChannel" AS ENUM ('', 'green', 'yellow', 'red');

-- CreateEnum
CREATE TYPE "ImportGoodsSource" AS ENUM ('manual', 'from_declaration', 'lark_import');

-- AlterTable: #08 declaration-line columns added to #07's TransportFileItem.
-- ⚠⚠⚠ declared_value is USD, freight_alloc is VND — never add them together
-- (bug caught at cls.container.php:707). ⚠⚠ antidumping_pct is DECIMAL(6,4)
-- (fraction-shaped) but the production convention is PERCENT (enter 5 for
-- 5%, not 0.05) — see schema.prisma comment on this column.
ALTER TABLE "tbl_transport_file_items" ADD COLUMN     "antidumping_pct" DECIMAL(6,4),
ADD COLUMN     "consumption_tax_rate" DECIMAL(5,2),
ADD COLUMN     "declared_name_vi" VARCHAR(500),
ADD COLUMN     "declared_value" DECIMAL(15,2),
ADD COLUMN     "duty_cbpg_amt" DECIMAL(18,2),
ADD COLUMN     "duty_nk_amt" DECIMAL(18,2),
ADD COLUMN     "duty_ttdb_amt" DECIMAL(18,2),
ADD COLUMN     "duty_vat_amt" DECIMAL(18,2),
ADD COLUMN     "envtax_amount" DECIMAL(14,2),
ADD COLUMN     "envtax_vnd" DECIMAL(18,2),
ADD COLUMN     "freight_alloc" DECIMAL(18,2),
ADD COLUMN     "import_duty_rate" DECIMAL(5,2),
ADD COLUMN     "quote_item_id" INTEGER,
ADD COLUMN     "tax_base" DECIMAL(18,2),
ADD COLUMN     "tax_rate_used" DECIMAL(12,4),
ADD COLUMN     "total_tax" DECIMAL(15,2),
ADD COLUMN     "vat_rate" DECIMAL(5,2);

-- CreateTable
CREATE TABLE "tbl_customs_declarations" (
    "id" SERIAL NOT NULL,
    "file_id" INTEGER,
    "declaration_number" VARCHAR(50),
    "declaration_date" DATE,
    "customs_office" TEXT,
    "customs_gate" TEXT,
    "decl_type" TEXT,
    "declarant_type" TEXT,
    "declarant_customer_id" TEXT,
    "status" INTEGER NOT NULL DEFAULT 0,
    "channel" "CustomsChannel" NOT NULL DEFAULT '',
    "total_declared_value" DECIMAL(15,2),
    "total_tax" DECIMAL(15,2),
    "total_vat" DECIMAL(15,2),
    "total_import_duty" DECIMAL(15,2),
    "registered_at" TIMESTAMP(3),
    "clearance_date" DATE,
    "tax_paid_at" TIMESTAMP(3),
    "tax_paid_by" TEXT,
    "frozen_json" TEXT,
    "frozen_at" TIMESTAMP(3),
    "hq_precheck_sent_at" INTEGER,
    "hq_precheck_sent_by" TEXT,
    "hq_precheck_ok_at" INTEGER,
    "hq_precheck_ok_by" TEXT,
    "hq_precheck_note" TEXT,
    "attachments" TEXT,
    "notes" TEXT,
    "created_by" TEXT,
    "created_at" INTEGER,

    CONSTRAINT "tbl_customs_declarations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tbl_import_goods" (
    "id" SERIAL NOT NULL,
    "goods_key" VARCHAR(500),
    "product_name" TEXT,
    "spec" TEXT,
    "hs_code" VARCHAR(20),
    "declared_name_vi" TEXT,
    "declared_name_en" TEXT,
    "declared_name_cn" TEXT,
    "ten_chung" TEXT,
    "declared_description" TEXT,
    "brand" TEXT,
    "model_code" TEXT,
    "material" TEXT,
    "manufacturer" TEXT,
    "declared_unit" TEXT,
    "sl2_unit" TEXT,
    "hq_unit1_cn" TEXT,
    "hq_unit2_cn" TEXT,
    "import_duty_rate" DECIMAL(5,2),
    "consumption_tax_rate" DECIMAL(5,2),
    "vat_rate" DECIMAL(5,2),
    "min_declared_price_usd" DECIMAL(15,4),
    "max_declared_price_usd" DECIMAL(15,4),
    "last_declared_price_usd" DECIMAL(15,4),
    "co_form" TEXT,
    "procedure_type" TEXT,
    "procedure_days" TEXT,
    "policy_notes" TEXT,
    "goods_condition" TEXT,
    "hs_status" INTEGER NOT NULL DEFAULT 0,
    "approved_by" TEXT,
    "approved_at" INTEGER,
    "hs_version" INTEGER,
    "pending_json" TEXT,
    "pending_by" TEXT,
    "pending_at" INTEGER,
    "source" "ImportGoodsSource",
    "times_used" INTEGER,
    "cleared_count" INTEGER,
    "last_cleared_at" INTEGER,
    "last_cleared_cont" TEXT,

    CONSTRAINT "tbl_import_goods_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tbl_hs_tariff" (
    "id" SERIAL NOT NULL,
    "hs_raw" VARCHAR(30),
    "hs_norm" VARCHAR(20),
    "hs_level" INTEGER,
    "desc_vi" TEXT,
    "desc_en" TEXT,
    "unit" TEXT,
    "nk_tt" VARCHAR(40),
    "nk_uu_dai" VARCHAR(40),
    "vat" VARCHAR(40),
    "acfta" VARCHAR(40),
    "rcep" VARCHAR(40),
    "ttdb" VARCHAR(40),
    "xk" VARCHAR(40),
    "bvmt" VARCHAR(60),
    "chinh_sach" TEXT,
    "giam_vat" TEXT,

    CONSTRAINT "tbl_hs_tariff_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tbl_customs_unit_rules" (
    "id" SERIAL NOT NULL,
    "scope_type" TEXT,
    "scope_key" TEXT,
    "unit1" TEXT,
    "unit2" TEXT,
    "conversion_type" TEXT,
    "factor" DECIMAL(18,6),
    "params_json" TEXT,

    CONSTRAINT "tbl_customs_unit_rules_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "tbl_customs_declarations_file_id_idx" ON "tbl_customs_declarations"("file_id");

-- CreateIndex
CREATE INDEX "tbl_customs_declarations_declaration_number_idx" ON "tbl_customs_declarations"("declaration_number");

-- CreateIndex
CREATE INDEX "tbl_customs_declarations_status_idx" ON "tbl_customs_declarations"("status");

-- CreateIndex
CREATE INDEX "tbl_import_goods_product_name_idx" ON "tbl_import_goods"("product_name");

-- CreateIndex
CREATE INDEX "tbl_import_goods_hs_code_idx" ON "tbl_import_goods"("hs_code");

-- CreateIndex
CREATE INDEX "tbl_hs_tariff_hs_norm_idx" ON "tbl_hs_tariff"("hs_norm");

-- CreateIndex
CREATE INDEX "tbl_customs_unit_rules_scope_type_idx" ON "tbl_customs_unit_rules"("scope_type");

-- CreateIndex
CREATE INDEX "tbl_transport_file_items_quote_item_id_idx" ON "tbl_transport_file_items"("quote_item_id");
