apiVersion: v1
kind: Service
metadata:
  name: tbs-postgres
  namespace: tbs-erp
  labels:
    app.kubernetes.io/name: tbs-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: tbs-erp-system
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: tbs-postgres
    app.kubernetes.io/component: database
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
