/**
 * Central error code registry.
 *
 * All error codes used across the application are defined here as string constants.
 * This ensures consistency, prevents typos, and enables type-safe error handling.
 *
 * Naming convention: DOMAIN_ACTION or DOMAIN_STATE
 * - Common HTTP: matches HTTP semantics (VALIDATION_ERROR, NOT_FOUND, etc.)
 * - Prisma-mapped: prefixed with DB_ (DB_UNIQUE_VIOLATION, etc.)
 * - Domain-specific: prefixed with entity name (ORDER_NOT_FOUND, etc.)
 */
export const ErrorCode = {
  // ─── Common HTTP ───
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',

  // ─── Prisma-mapped ───
  DB_UNIQUE_VIOLATION: 'DB_UNIQUE_VIOLATION',
  DB_FK_VIOLATION: 'DB_FK_VIOLATION',
  DB_RECORD_NOT_FOUND: 'DB_RECORD_NOT_FOUND',
  DB_RELATION_VIOLATION: 'DB_RELATION_VIOLATION',
  DB_TABLE_NOT_FOUND: 'DB_TABLE_NOT_FOUND',
  DB_TIMEOUT: 'DB_TIMEOUT',
  DB_VALIDATION_ERROR: 'DB_VALIDATION_ERROR',

  // ─── Order ───
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_INVALID_TRANSITION: 'ORDER_INVALID_TRANSITION',
  ORDER_ALREADY_COMPLETED: 'ORDER_ALREADY_COMPLETED',
  ORDER_ALREADY_CANCELLED: 'ORDER_ALREADY_CANCELLED',
  ORDER_CREATION_FAILED: 'ORDER_CREATION_FAILED',
  INSUFFICIENT_DEPOSIT: 'INSUFFICIENT_DEPOSIT',

  // ─── Auth ───
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_2FA_CODE: 'INVALID_2FA_CODE',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  API_KEY_NOT_FOUND: 'API_KEY_NOT_FOUND',

  // ─── Container ───
  CONTAINER_NOT_FOUND: 'CONTAINER_NOT_FOUND',
  CONTAINER_INVALID_TRANSITION: 'CONTAINER_INVALID_TRANSITION',

  // ─── CRM / Customer ───
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_INACTIVE: 'CUSTOMER_INACTIVE',
  CUSTOMER_BLOCKED: 'CUSTOMER_BLOCKED',

  // ─── Finance ───
  VOUCHER_NOT_FOUND: 'VOUCHER_NOT_FOUND',
  VOUCHER_INVALID_STATE: 'VOUCHER_INVALID_STATE',
  VOUCHER_FRAUD_FLAG: 'VOUCHER_FRAUD_FLAG',
  PAYMENT_FAILED: 'PAYMENT_FAILED',

  // ─── Complaint ───
  COMPLAINT_CREATION_FAILED: 'COMPLAINT_CREATION_FAILED',

  // ─── Customs ───
  CUSTOMS_NOT_FOUND: 'CUSTOMS_NOT_FOUND',
  CUSTOMS_INVALID_TRANSITION: 'CUSTOMS_INVALID_TRANSITION',

  // ─── Approval ───
  APPROVAL_FAILED: 'APPROVAL_FAILED',
  APPROVAL_CONDITION_PARSE_ERROR: 'APPROVAL_CONDITION_PARSE_ERROR',

  // ─── Integration ───
  INTEGRATION_SYNC_ERROR: 'INTEGRATION_SYNC_ERROR',
  INTEGRATION_HANDLER_NOT_FOUND: 'INTEGRATION_HANDLER_NOT_FOUND',

  // ─── Infrastructure ───
  ENCRYPTION_ERROR: 'ENCRYPTION_ERROR',
  VAULT_ERROR: 'VAULT_ERROR',
  TRANSACTION_ERROR: 'TRANSACTION_ERROR',

  // ─── WebSocket ───
  WS_AUTH_REQUIRED: 'WS_AUTH_REQUIRED',
  WS_AUTH_FAILED: 'WS_AUTH_FAILED',
  WS_ACCOUNT_INACTIVE: 'WS_ACCOUNT_INACTIVE',
  WS_INVALID_CHANNEL: 'WS_INVALID_CHANNEL',
  WS_UNAUTHORIZED_CHANNEL: 'WS_UNAUTHORIZED_CHANNEL',
  WS_MAX_SUBSCRIPTIONS: 'WS_MAX_SUBSCRIPTIONS',

  // ─── BullMQ ───
  JOB_PROCESSING_FAILED: 'JOB_PROCESSING_FAILED',

  // ─── Automation ───
  AUTOMATION_ACTION_FAILED: 'AUTOMATION_ACTION_FAILED',

  // ─── Batch Import ───
  BATCH_IMPORT_VALIDATION_ERROR: 'BATCH_IMPORT_VALIDATION_ERROR',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
