apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tbs-erp-staging

namePrefix: staging-

commonLabels:
  environment: staging

resources:
  - ../../base

patches:
  - path: patches/backend-replicas.yaml
  - path: patches/resource-limits.yaml
  - path: patches/ingress-host.yaml
